### ISSUE TITLE
getInstance error

### ISSUE THREAD

**Issue by ChristianRazvan** [truecaller/android-sdk#28]
In the read-me file step 6 comes before 7 but if i run 
`TrueSDK.getInstance();`  
i am getting the error : 
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.intersoft.chris.intersoftcalllog, PID: 28807
                  java.lang.RuntimeException: Please call init() on TrueSDK first
                      at com.truecaller.android.sdk.TrueSDK.getInstance(Unknown Source)
                      at com.intersoft.chris.intersoftcalllog.PhoneCallListener.onCallStateChanged(PhoneCallListener.java:51)
                      at android.telephony.PhoneStateListener$1.handleMessage(PhoneStateListener.java:293)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by aripuzo** [comment]
Any solution for this?

**Comment by ChristianRazvan** [comment]
I abandoned the use of true call but from what i remember i created first the scope then init and after that i got the instance.
