### ISSUE TITLE
TrueButton is always null

### ISSUE THREAD

**Issue by GurpreetSK95** [truecaller/android-sdk#3]
I am always getting a NPE on trying to set the TrueClient to the TrueButton.

```
FATAL EXCEPTION: main
                                                                            Process: me.gurpreetsk.emicalulator, PID: 16419
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{me.gurpreetsk.emicalulator/me.gurpreetsk.emicalulator.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.truecaller.android.sdk.TrueButton.setTrueClient(com.truecaller.android.sdk.TrueClient)' on a null object reference
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.truecaller.android.sdk.TrueButton.setTrueClient(com.truecaller.android.sdk.TrueClient)' on a null object reference
                                                                                at me.gurpreetsk.emicalulator.LoginActivity.onCreate(LoginActivity.java:41)
                                                                                at android.app.Activity.performCreate(Activity.java:6679)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by GurpreetSK95** [comment]
Turns out you have to provide the exact same ID as given in the docs: com_truecaller_android_sdk_truebutton

**Comment by shaz-tech** [comment]
WTF. why the name is mandatory to set from their end.
