### ISSUE TITLE
SDK fails in absence of Truecaller on device

### ISSUE THREAD

**Issue by shouryalala** [truecaller/android-sdk#32]

**Comment by shouryalala** [comment]
Firstly, the updates to the sdk now dont allow TrueSDK.getInstance().isUsable() to be called before the init() method. 
So there is no way of inspecting Truecaller's presence on the device without first buidling the TrueSDK object.

Secondly even if i do toggle OTP verification I get the following error
    "... FATAL EXCEPTION: main
 Process: com.project.xyz.userclientapp, PID: 25694 java.lang.NoClassDefFoundError:
 Failed resolution of: Lretrofit2/converter/gson/GsonConverterFactory;
 at com.truecaller.android.sdk.b.c.a(Unknown Source:9)
 at com.truecaller.android.sdk.clients.a.<init>(Unknown Source:10)
 at com.truecaller.android.sdk.a.<init>(Unknown Source:46)
 at com.truecaller.android.sdk.a.a(Unknown Source:2)
 at com.truecaller.android.sdk.TrueSDK.init(Unknown Source:5)
 at com.project.xyz.userclientapp.login.LoginActivity.setupTrueSdk(LoginActivity.java:49)
 at com.project.xyz.userclientapp.login.LoginActivity.onCreate(LoginActivity.java:30)
 at android.app.Activity.performCreate(Activity.java:7149)
 at android.app.Activity.performCreate(Activity.java:7140)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 at ...."
