### ISSUE TITLE
Unfortunatly stoping  mTrueClient.generateRequestNonce(); statement

### ISSUE THREAD

**Issue by Narender-350** [truecaller/android-sdk#6]
Logcat:  
     E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.ex.truecalertemp, PID: 17763
                                                   java.lang.RuntimeException: Unable to resume activity {com.onexsoftech.truecalertemp/com.ex.truecalertemp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.truecaller.android.sdk.TrueClient.generateRequestNonce()' on a null object reference
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3136)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3167)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2514)
                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.truecaller.android.sdk.TrueClient.generateRequestNonce()' on a null object reference
                                                       at com.onexsoftech.truecalertemp.MainActivity.onResume(MainActivity.java:77)
                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                       at android.app.Activity.performResume(Activity.java:6379)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3125)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3167) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2514) 
                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5529) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by codevalley** [comment]
Can you throw in additional info on this?

**Comment by codevalley** [comment]
@Narender-350 I think this is because you are calling  `mTrueClient.generateRequestNonce() `on the `onResume()` of your activity. I don't think you should call it there, without first checking if `TrueClient` is `null` or not.

**Comment by Narender-350** [comment]
Thanks for replay..

mTrueClient.generateRequestNonce()  getting here always null even if i write in onpause or onResume or anywhere
